### ISSUE TITLE
Redirect on if no index on RAW

### ISSUE THREAD

**Issue by Jacxk** [SourceBin/SourceBin#10]
I would be cool if when you go to `/raw/:key/` it would redirect you to `/raw/:key/0`. Since 0 is the default why not just make `/raw/:key/` go to the default one.

**Comment by SebastiaanYN** [comment]
I don't think redirecting `/raw/:key` to `/raw/:key/0` is something that would have a use.

Instead, I think it might be possible to display all files at once when going to `/raw/:key`.

**Comment by Jacxk** [comment]
That also works but you have to make it so people can differentiate between files

**Comment by SebastiaanYN** [comment]
I don't feel like there's a significant enough reason to redirect to the first file by default. Most people won't visit the raw content by writing the URL themselves.
