### ISSUE TITLE
An array of every language that is accepted.

### ISSUE THREAD

**Issue by xaxa-0x3F** [SourceBin/SourceBin#26]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like an array of every language that can be formatted using sourcebin

**Describe alternatives you've considered**

**Additional context**

**Comment by ghostdevv** [comment]
The languages.json file in here has what you are looking for, you can import that file via npm and then turn it to an array with `Object.values(languages)`

**Comment by xaxa-0x3F** [comment]
I did import the package, but now 

> The languages.json file in here has what you are looking for, you can import that file via npm and then turn it to an array with `Object.values(languages)`

I imported the npm package but I feel really dumb because I'm not the best programmer and don't know how to import just that file......please help.

**Comment by ghostdevv** [comment]
First install the package `npm i @sourcebin/linguist`

Then in your code you can do:
```js
const linguist = require('@sourcebin/linguist');
const languages = Object.keys(linguist.languages);
```

@ehAsuna

**Comment by xaxa-0x3F** [comment]
> First install the package `npm i @sourcebin/linguist`
> 
> Then in your code you can do:
> 
> ```js
> const linguist = require('@sourcebin/linguist');
> const languages = Object.keys(linguist.languages);
> ```
> 
> @ehAsuna

Thank you very much ghost! I appreciate it.

**Comment by ghostdevv** [comment]
Np
